### ISSUE TITLE
Play animation when loadout is selected

### ISSUE THREAD

**Issue by bigdonabele** [jbrown215/TF146-scripts#3]
Currently other players can see an animation when a user first selects a loadout, however, the actual use does not have anything from their POV.   This is a minor quality of life feature, but would like to see an animation when a loadout is switched or selected by the user themselves.

**Comment by jbrown215** [comment]
Oh, I thought the issue was in the opposite direction. To confirm: when you select a loadout everyone else sees you do an animation?

**Comment by bigdonabele** [comment]
Yes others can see the user getting the loadout do an animation, however from the user using the arsenal there is no animation played.
